#pragma once

#include <stdint.h>

constexpr uint64_t DISPATCH_FFN_COMBINE_DEVICE_TILING_KEY = 1000010UL;
constexpr uint64_t DISPATCH_FFN_COMBINE_STANDALONE_FUNC_KEY = 0UL;
constexpr uint64_t DISPATCH_FFN_COMBINE_SYS_CNT_NS_PER_TICK = 20UL;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_ENTRY_BYTES = 2048U;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_ENTRIES_PER_BLOCK = 3U;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_BYTES_PER_BLOCK =
    DISPATCH_FFN_COMBINE_PROFILE_ENTRY_BYTES * DISPATCH_FFN_COMBINE_PROFILE_ENTRIES_PER_BLOCK;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_KERNEL_START = 0U;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_KERNEL_END = 1U;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_STAGE_BASE = 2U;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_STAGE_COUNT = 7U;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_GMM1_DETAIL_BASE =
    DISPATCH_FFN_COMBINE_PROFILE_STAGE_BASE + DISPATCH_FFN_COMBINE_PROFILE_STAGE_COUNT * 2U;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_GMM1_DETAIL_FIELD_COUNT = 4U;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_GMM1_DETAIL_MAX_EXPERTS = 16U;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_BASE =
    DISPATCH_FFN_COMBINE_PROFILE_GMM1_DETAIL_BASE +
    DISPATCH_FFN_COMBINE_PROFILE_GMM1_DETAIL_MAX_EXPERTS *
        DISPATCH_FFN_COMBINE_PROFILE_GMM1_DETAIL_FIELD_COUNT;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_FIELD_COUNT = 4U;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_COUNT = 30U;
constexpr uint32_t DISPATCH_FFN_COMBINE_PROFILE_ENTRY_U64_COUNT =
    DISPATCH_FFN_COMBINE_PROFILE_ENTRY_BYTES / sizeof(uint64_t);

enum DispatchFFNCombineProfileStage : uint32_t {
    DISPATCH_FFN_COMBINE_PROFILE_STAGE_FRONT = 0U,
    DISPATCH_FFN_COMBINE_PROFILE_STAGE_DISPATCH = 1U,
    DISPATCH_FFN_COMBINE_PROFILE_STAGE_GMM1 = 2U,
    DISPATCH_FFN_COMBINE_PROFILE_STAGE_SWIGLU = 3U,
    DISPATCH_FFN_COMBINE_PROFILE_STAGE_GMM2 = 4U,
    DISPATCH_FFN_COMBINE_PROFILE_STAGE_COMBINE = 5U,
    DISPATCH_FFN_COMBINE_PROFILE_STAGE_UNPERMUTE = 6U,
};

enum DispatchFFNCombineProfileFrontDetail : uint32_t {
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_TOTAL = 0U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ACTIVE_MASK = 1U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_INIT_ROUTING = 2U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_SYNC_AFTER_INIT = 3U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ALLGATHER_TOTAL = 4U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ALLGATHER_PUBLISH = 5U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ALLGATHER_PUBLISH_LOAD = 6U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ALLGATHER_PUBLISH_MARK = 7U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ALLGATHER_PUBLISH_STORE = 8U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ALLGATHER_RESTORE_TOTAL = 9U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ALLGATHER_WAIT_MARKER = 10U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ALLGATHER_RESTORE_LOAD = 11U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ALLGATHER_RESTORE_UNMARK = 12U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ALLGATHER_PRESUM = 13U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ALLGATHER_STORE_PRESUM = 14U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_ALLGATHER_FINAL_SYNC = 15U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_CUMSUM_TOTAL = 16U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_CUMSUM_LOAD = 17U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_CUMSUM_VECTOR_ADD = 18U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_CUMSUM_STORE = 19U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_PREV_SUM_READ = 20U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_SYNC_AFTER_CUMSUM = 21U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_EXPERT_NUMS_COPY = 22U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_NOTIFY_GMM1 = 23U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_DISPATCH_SETUP_FLAGS = 24U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_DISPATCH_GROUP_SYNC = 25U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_DISPATCH_COPY_TOTAL = 26U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_COMBINE_TOTAL = 27U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_UNPERMUTE_TOTAL = 28U,
    DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_RESERVED = 29U,
};

constexpr uint32_t DispatchFFNCombineProfileStageStartIndex(uint32_t stage)
{
    return DISPATCH_FFN_COMBINE_PROFILE_STAGE_BASE + stage * 2U;
}

constexpr uint32_t DispatchFFNCombineProfileStageEndIndex(uint32_t stage)
{
    return DispatchFFNCombineProfileStageStartIndex(stage) + 1U;
}

constexpr uint32_t DispatchFFNCombineProfileGmm1DetailStartIndex(uint32_t expert)
{
    return DISPATCH_FFN_COMBINE_PROFILE_GMM1_DETAIL_BASE +
           expert * DISPATCH_FFN_COMBINE_PROFILE_GMM1_DETAIL_FIELD_COUNT;
}

constexpr uint32_t DispatchFFNCombineProfileGmm1DetailEndIndex(uint32_t expert)
{
    return DispatchFFNCombineProfileGmm1DetailStartIndex(expert) + 1U;
}

constexpr uint32_t DispatchFFNCombineProfileGmm1DetailTotalIndex(uint32_t expert)
{
    return DispatchFFNCombineProfileGmm1DetailStartIndex(expert) + 2U;
}

constexpr uint32_t DispatchFFNCombineProfileGmm1DetailCountIndex(uint32_t expert)
{
    return DispatchFFNCombineProfileGmm1DetailStartIndex(expert) + 3U;
}

static_assert(DispatchFFNCombineProfileGmm1DetailCountIndex(
                  DISPATCH_FFN_COMBINE_PROFILE_GMM1_DETAIL_MAX_EXPERTS - 1U) <
              DISPATCH_FFN_COMBINE_PROFILE_ENTRY_U64_COUNT);

constexpr uint32_t DispatchFFNCombineProfileFrontDetailStartIndex(uint32_t detail)
{
    return DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_BASE +
           detail * DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_FIELD_COUNT;
}

constexpr uint32_t DispatchFFNCombineProfileFrontDetailEndIndex(uint32_t detail)
{
    return DispatchFFNCombineProfileFrontDetailStartIndex(detail) + 1U;
}

constexpr uint32_t DispatchFFNCombineProfileFrontDetailTotalIndex(uint32_t detail)
{
    return DispatchFFNCombineProfileFrontDetailStartIndex(detail) + 2U;
}

constexpr uint32_t DispatchFFNCombineProfileFrontDetailCountIndex(uint32_t detail)
{
    return DispatchFFNCombineProfileFrontDetailStartIndex(detail) + 3U;
}

static_assert(DispatchFFNCombineProfileFrontDetailCountIndex(
                  DISPATCH_FFN_COMBINE_PROFILE_FRONT_DETAIL_COUNT - 1U) <
              DISPATCH_FFN_COMBINE_PROFILE_ENTRY_U64_COUNT);

struct DispatchFFNCombineLaunchArgs {
    void *x = nullptr;
    void *weight1 = nullptr;
    void *weight2 = nullptr;
    void *expert_idx = nullptr;
    void *scale1 = nullptr;
    void *scale2 = nullptr;
    void *probs = nullptr;
    void *x_active_mask = nullptr;
    void *out = nullptr;
    void *expert_token_nums = nullptr;
    void *workspace = nullptr;
    void *tiling = nullptr;
    void *profile_data = nullptr;
    uint32_t block_dim = 1;
    uint32_t stage_profile = 0;
    uint32_t start_sync_debug = 0;
    uint64_t func_key = DISPATCH_FFN_COMBINE_STANDALONE_FUNC_KEY;
};

uint32_t launchDispatchFFNCombine(const DispatchFFNCombineLaunchArgs &args, void *stream);
